### ISSUE TITLE
Is this like SubHook?

### ISSUE THREAD

**Issue by polarathene** [geofft/redhook#7]
I'm looking into Rust alternatives to [SubHook](https://github.com/Zeex/subhook), I'm new to this type of thing. How does it compare to SubHook? Is there any plans for supporting Windows?

**Comment by geofft** [comment]
It's similar. It looks like SubHook works by re-mapping a function's memory as writable and overwriting the first instruction with a jump. redhook uses the built in support of the dynamic linker on UNIX platforms to say, when you're looking for a symbol with this name, look in this library first. I don't believe Windows has directly similar functionality, but it does have IAT patching, which at least involves overwriting the lookup table for functions instead of overwriting the functions themselves (which means you can wrap a call to the real function; I think if you overwrite the old function you don't get to do that any more).

I don't do any Windows dev these days so I'm not particularly planning on adding Windows support, but I wouldn't say no to a pull request.
